//
// WARNING: this module is autogenerated. Do not edit this file!
//

import {Tuple, addTupleType} from "@synerty/vortexjs";

//
// Types
//{% for tp in types %}
{% if not tp.is_alias %}
@addTupleType
export class {{ tp.class_name }} extends Tuple {
    static readonly tupleName = {{ tp.tupleType }};
    {%- for name, pyType, jsType, pyVal, jsVal in tp.fields %}
    {{ name }}: {{jsType}}{{ jsVal }};
    {%- endfor %}

    constructor() {
        super({{ tp.class_name }}.tupleName);
    }
}
{% endif %}{% endfor %}
